### PR TITLE
Build JavaScript using Pacel

### PR DESCRIPTION
**Pull request by aminya**
This speeds up the loading time by tree-shaking and prebuilding CoffeeScript

### CODE REVIEW

**Comment by aminya** [comment]
This does not work yet because of https://github.com/prebuild/node-gyp-build/issues/22

**Comment by aminya** [comment]
I fixed the problem by setting the dist as the root folder.

**Comment by rajendrant** [comment]
I wonder if using the parcel library is not needed, if we convert the coffee (only one main file) to js.
The other changes in the PR like babel, shx, cross-env are certainly fine.

**Comment by aminya** [comment]
The main benefit of using this is to use Parcel to tree-shake the dependencies. For example, we don't use all of the original `fuzzaldrin-plus`. This bundles and minifies the whole thing which loads much faster.

Original size: 27.69
New size: 10.77

This is a typical performance improvement pattern we have found by testing many packages in our organization.

**Comment by aminya** [comment]
All the tests pass. I will merge this!

**Pull request merged**
