### PR TITLE
chore: fix build on apple silicon

### PR DESCRIPTION
**Pull request by cdaguerre**
@aminya I don't know if this helps but this is intended to backport silicon builds to v2.0.2...
Could you tag 2.0.3 afterwards?

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Ah, thank you! I had almost finished #58. But sure we can support v2 too. Could you add the same flags to the Debug build?

**Review by aminya — CHANGES_REQUESTED** [review]
Once you run Node, what does the following code return?
```js
console.log(process.arch)
```

We need to also add a prebuildify script for that arch with `--arch=what_the_above_returns`.

**Comment by cdaguerre** [comment]
```sh
$ node -e 'console.log(process.arch)'
arm64
```

**Comment by aminya** [comment]
@cdaguerre As I expected there is no Node arm64. I think we should rely on you for the prebuilds and testing.

**Comment by aminya** [comment]
@cdaguerre Could you run the prebuildify-arm64 and provide me the built `.node` file?

**Pull request merged**
